package catalog

func defaultVideoCodecs() []VideoCodec {
	x264x265Presets := []string{
		"ultrafast", "superfast", "veryfast", "faster", "fast",
		"medium", "slow", "slower", "veryslow", "placebo",
	}
	nvencPresets := []string{"p1", "p2", "p3", "p4", "p5", "p6", "p7"}
	svtAv1Presets := []string{"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"}

	return []VideoCodec{
		{
			Name:        "libx264",
			Family:      FamilyCPU,
			DisplayName: "H.264 (libx264)",
			Description: "Software H.264 — broad compatibility, mature.",
			Presets:     x264x265Presets,
			Tunes:       []string{"film", "animation", "grain", "stillimage", "fastdecode", "zerolatency"},
			Profiles:    []string{"baseline", "main", "high", "high10", "high422", "high444"},
			Levels:      []string{"3.0", "3.1", "3.2", "4.0", "4.1", "4.2", "5.0", "5.1", "5.2", "6.0", "6.1", "6.2"},
			PixelFormats: []string{"yuv420p", "yuv420p10le", "yuv422p", "yuv422p10le", "yuv444p", "yuv444p10le"},
			CRFRange:    &IntRange{Min: 0, Max: 51, Default: 23},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateABR},
			AllowsTwoPass: true,
			ParamFlag:   "-x264-params",
		},
		{
			Name:        "libx265",
			Family:      FamilyCPU,
			DisplayName: "HEVC (libx265)",
			Description: "Software HEVC — better compression than H.264, slower.",
			Presets:     x264x265Presets,
			Tunes:       []string{"animation", "grain", "fastdecode", "zerolatency"},
			Profiles:    []string{"main", "main10", "main12", "main422-10", "main444-8", "main444-10"},
			Levels:      []string{"3.0", "3.1", "4.0", "4.1", "5.0", "5.1", "5.2", "6.0", "6.1", "6.2"},
			PixelFormats: []string{"yuv420p", "yuv420p10le", "yuv422p", "yuv422p10le", "yuv444p", "yuv444p10le"},
			CRFRange:    &IntRange{Min: 0, Max: 51, Default: 28},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateABR},
			AllowsTwoPass: true,
			ParamFlag:   "-x265-params",
		},
		{
			Name:        "libsvtav1",
			Family:      FamilyCPU,
			DisplayName: "AV1 (SVT-AV1)",
			Description: "Software AV1 (SVT-AV1) — efficient, modern. CRF range is wider than h264/265.",
			Presets:     svtAv1Presets,
			PixelFormats: []string{"yuv420p", "yuv420p10le"},
			CRFRange:    &IntRange{Min: 0, Max: 63, Default: 35},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateABR},
			AllowsTwoPass: true,
			ParamFlag:   "-svtav1-params",
		},
		{
			Name:        "libvpx-vp9",
			Family:      FamilyCPU,
			DisplayName: "VP9 (libvpx-vp9)",
			Description: "Software VP9 — WebM-friendly.",
			PixelFormats: []string{"yuv420p", "yuv420p10le", "yuv422p", "yuv440p", "yuv444p"},
			CRFRange:    &IntRange{Min: 0, Max: 63, Default: 31},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateABR},
			AllowsTwoPass: true,
		},
		{
			Name:        "libaom-av1",
			Family:      FamilyCPU,
			DisplayName: "AV1 (libaom)",
			Description: "Reference AV1 — highest quality, slowest.",
			PixelFormats: []string{"yuv420p", "yuv420p10le"},
			CRFRange:    &IntRange{Min: 0, Max: 63, Default: 30},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateABR},
			AllowsTwoPass: true,
			ParamFlag:   "-aom-params",
		},
		{
			Name:        "h264_nvenc",
			Family:      FamilyNVENC,
			DisplayName: "H.264 (NVIDIA NVENC)",
			Description: "Hardware H.264 on NVIDIA GPUs. Pair with hwaccel=nvdec for full GPU pipeline.",
			Presets:     nvencPresets,
			Tunes:       []string{"hq", "ll", "ull", "lossless"},
			Profiles:    []string{"baseline", "main", "high", "high444p"},
			Levels:      []string{"auto", "3.0", "3.1", "4.0", "4.1", "5.0", "5.1", "5.2", "6.0", "6.1", "6.2"},
			PixelFormats: []string{"yuv420p", "nv12", "p010le"},
			QPRange:     &IntRange{Min: 0, Max: 51, Default: 23},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateQP},
			AllowsTwoPass: false,
		},
		{
			Name:        "hevc_nvenc",
			Family:      FamilyNVENC,
			DisplayName: "HEVC (NVIDIA NVENC)",
			Description: "Hardware HEVC on NVIDIA GPUs.",
			Presets:     nvencPresets,
			Tunes:       []string{"hq", "ll", "ull", "lossless"},
			Profiles:    []string{"main", "main10", "rext"},
			Levels:      []string{"auto", "3.0", "3.1", "4.0", "4.1", "5.0", "5.1", "5.2", "6.0", "6.1", "6.2"},
			PixelFormats: []string{"yuv420p", "nv12", "p010le"},
			QPRange:     &IntRange{Min: 0, Max: 51, Default: 28},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateQP},
			AllowsTwoPass: false,
		},
		{
			Name:        "av1_nvenc",
			Family:      FamilyNVENC,
			DisplayName: "AV1 (NVIDIA NVENC, RTX 40+)",
			Description: "Hardware AV1 on Ada-generation NVIDIA GPUs.",
			Presets:     nvencPresets,
			PixelFormats: []string{"yuv420p", "nv12", "p010le"},
			QPRange:     &IntRange{Min: 0, Max: 63, Default: 30},
			RateModes:   []RateMode{RateCRF, RateCBR, RateVBR, RateQP},
			AllowsTwoPass: false,
		},
		{
			Name:        "h264_vaapi",
			Family:      FamilyVAAPI,
			DisplayName: "H.264 (VAAPI)",
			Description: "Hardware H.264 via VAAPI (Intel/AMD on Linux).",
			Profiles:    []string{"constrained_baseline", "main", "high"},
			Levels:      []string{"3.0", "3.1", "4.0", "4.1", "4.2", "5.0", "5.1"},
			PixelFormats: []string{"nv12", "vaapi"},
			QPRange:     &IntRange{Min: 0, Max: 51, Default: 23},
			RateModes:   []RateMode{RateCBR, RateVBR, RateQP},
		},
		{
			Name:        "hevc_vaapi",
			Family:      FamilyVAAPI,
			DisplayName: "HEVC (VAAPI)",
			Description: "Hardware HEVC via VAAPI.",
			Profiles:    []string{"main", "main10"},
			PixelFormats: []string{"nv12", "p010le", "vaapi"},
			QPRange:     &IntRange{Min: 0, Max: 51, Default: 28},
			RateModes:   []RateMode{RateCBR, RateVBR, RateQP},
		},
		{
			Name:        "h264_qsv",
			Family:      FamilyQSV,
			DisplayName: "H.264 (Intel Quick Sync)",
			Description: "Hardware H.264 via Intel QSV.",
			Presets:     []string{"veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow"},
			Profiles:    []string{"baseline", "main", "high"},
			PixelFormats: []string{"nv12", "qsv"},
			QPRange:     &IntRange{Min: 1, Max: 51, Default: 23},
			RateModes:   []RateMode{RateCBR, RateVBR, RateQP},
		},
		{
			Name:        "hevc_qsv",
			Family:      FamilyQSV,
			DisplayName: "HEVC (Intel Quick Sync)",
			Description: "Hardware HEVC via Intel QSV.",
			Presets:     []string{"veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow"},
			Profiles:    []string{"main", "main10"},
			PixelFormats: []string{"nv12", "p010le", "qsv"},
			QPRange:     &IntRange{Min: 1, Max: 51, Default: 28},
			RateModes:   []RateMode{RateCBR, RateVBR, RateQP},
		},
		{
			Name:        "copy",
			Family:      FamilyPassthru,
			DisplayName: "Copy (no re-encode)",
			Description: "Stream copy — passthrough; ignores codec params.",
			RateModes:   []RateMode{RateNone},
		},
	}
}

func defaultHwaccels() []Hwaccel {
	return []Hwaccel{
		{
			Type:        "none",
			DisplayName: "Software (no hardware acceleration)",
			CodecNames:  []string{"libx264", "libx265", "libsvtav1", "libvpx-vp9", "libaom-av1", "copy"},
			OutputFmts:  nil,
		},
		{
			Type:        "nvdec",
			DisplayName: "NVIDIA NVDEC/CUDA",
			Description: "Decode and process on NVIDIA GPU. Pair with NVENC encoders.",
			CodecNames:  []string{"h264_nvenc", "hevc_nvenc", "av1_nvenc"},
			OutputFmts:  []string{"cuda", "nv12", "p010le"},
			DefaultDev:  "",
		},
		{
			Type:        "vaapi",
			DisplayName: "VAAPI (Intel/AMD on Linux)",
			CodecNames:  []string{"h264_vaapi", "hevc_vaapi"},
			OutputFmts:  []string{"vaapi", "nv12"},
			DefaultDev:  "/dev/dri/renderD128",
		},
		{
			Type:        "qsv",
			DisplayName: "Intel Quick Sync Video",
			CodecNames:  []string{"h264_qsv", "hevc_qsv"},
			OutputFmts:  []string{"qsv", "nv12"},
			DefaultDev:  "/dev/dri/renderD128",
		},
		{
			Type:        "videotoolbox",
			DisplayName: "Apple VideoToolbox",
			CodecNames:  []string{"h264_videotoolbox", "hevc_videotoolbox"},
			OutputFmts:  []string{"videotoolbox_vld", "nv12"},
		},
	}
}
