version: 2
updates:
  - package-ecosystem: 'uv'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - dependencies
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - dependencies
