services:
  prefect-server:
    image: prefecthq/prefect:3.4.6-python3.13
    restart: always
    command: prefect server start
    volumes:
      - prefect-server:/root/.prefect
    environment:
      PREFECT_SERVER_API_HOST: "0.0.0.0"
      PREFECT_UI_URL: http://127.0.0.1:4200/api
      PREFECT_API_URL: http://127.0.0.1:4200/api
    ports:
      - 4200:4200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'python3 -c ''import urllib.request; urllib.request.urlopen("http://localhost:4200/api/health")''',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  prefect-process-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run watchfiles "uv run deploy.py all --environment local" /app
    volumes:
      - ./tidal:/app/tidal
      - ./deploy.py:/app/deploy.py
    depends_on:
      prefect-server:
        condition: service_started
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prefect-server:
