{{- if .Values.serviceAccount.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tidal.serverServiceAccount" . }}
  labels: {{- include "tidal.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
{{- if .Values.serviceAccount.dispatcher.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tidal.dispatcherServiceAccount" . }}
  labels: {{- include "tidal.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
{{- if .Values.serviceAccount.worker.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tidal.workerServiceAccount" . }}
  labels: {{- include "tidal.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
