apiVersion: v1
kind: Service
metadata:
  name: {{ include "tidal.fullname" . }}-server
  labels: {{- include "tidal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "tidal.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
